# Generated by Django 5.2.2 on 2025-06-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
