# Generated by Django 5.2.2 on 2025-06-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_heroimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': '6.Contact Us'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3.Course'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2.Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': '1.Users'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name_plural': '5.Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='heroimage',
            options={'verbose_name_plural': '7.Hero Images'},
        ),
        migrations.AlterField(
            model_name='heroimage',
            name='image_url',
            field=models.TextField(help_text='Image size should be 1920x500 upload anywhere on the internet then share the link here.'),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=100)),
                ('video_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='main.course')),
            ],
            options={
                'verbose_name_plural': '4.Modules',
            },
        ),
    ]
