# Generated by Django 5.2.2 on 2025-06-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_contactus_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='transaction_number',
            field=models.CharField(default='PENDING123', max_length=100),
            preserve_default=False,
        ),
    ]
