# Generated by Django 5.2.2 on 2025-06-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_enrollment_status_enrollment_transaction_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='transaction_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
