# Generated by Django 5.2.2 on 2025-06-17 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_moduleprogress'),
    ]

    operations = [
    ]
