# Generated by Django 5.2.2 on 2025-06-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20250617_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='intro_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
